from pydantic import BaseModel, Field

class BrokerConnectResponse(BaseModel):
    """
    Schema containing the Zerodha OAuth login URL generated by the backend.
    """
    login_url: str = Field(..., description="The authorization redirect URL for Zerodha login")
